credentials:
  usernames:
    user1:
      accounts: []
      name: Ben Hardman
      password: $2b$12$uN10zorE6hU9lyUjiyjkveBeJLUUoHMpC3sWRZ2oyF2DqREgpR49G
    user2:
      accounts: []
      name: John Toher
      password: $2b$12$1DghgmTJ5V.qcHN4Bg5VwOXQXkMBUvNtqXmZNz0o3Vb9fyAAtO5ii
    user3:
      accounts: []
      name: Oliver Newland
      password: $2b$12$8ej7ymDIjgJVrW0CO7QD5eUf9gG.IcEV6NCzMDtgA5wo7IOyVY7FS